### PR TITLE
Teletext button added

### PR DESCRIPTION
**Pull request by thehappyhippo**
Added Teletext button with visibility condition. Modified info with visibility condition. Renumbered buttons.

### CODE REVIEW

**Comment by tomer953** [comment]
hey, Thanks.

do you have a screenshot how it looks like?
did you test it on both layout of the skin, RTL\LTR ? (switch the language to Hebrew for example)
I'm very busy these days and I can't even test it, sorry.

**Comment by thehappyhippo** [comment]
Hello,
I tested RTL/LTR. Both behave the same with the Teletext button. Different languages (german is my default, english and hebrew tested also) and horizontal menu (my default) work also. Here is the Teletext button (red rectangle). The icon is available when teletext is present (see [VideoPlayer doc](http://kodi.wiki/view/Skinning_Manual#VideoPlayer)   )
teletext1
teletext2

_BTW: Don't be confused I moved the info button in my version. The pull request has the original position._

**Comment by tomer953** [comment]
Ok, looks good.
Thank you, merged.

**Comment by tomer953** [comment]
you forgot to update the id for "" to 913 as well,
it caused a bug which no submenu for the subtitle icon...

I will fix it by myself

**Pull request merged**
